# Generated by Django 3.0.6 on 2020-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_panaderia_redirectto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('redirectTo', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='panaderia',
            name='redirectTo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
